### PR TITLE
Add support for lbvserver_servicegroup_binding

### PR DESCRIPTION
**Pull request by davemcdonnell**
Ive been using lbvserver_service_binding to create servicegroup bindings which half works, but prefetch is broken and some parameters dont apply to servicegroups. Thought it best to put this in its own type.

I was able to get prefetching working in lbvserver_service_binding but it seemed a bit of a hack, as things like weight dont apply to servicegroup bindings.

### CODE REVIEW

**Comment by tphoney** [comment]
Would it be possible to get an acceptance test written for this. There are loads of examples to copy. Thanks again for the work you have put in.

**Comment by davemcdonnell** [comment]
I'd love to try but I'm fumbling my way through beaker/beaker-rspec and not getting anywhere very quickly.

Should I be able to run the rspec tests? They appear to reference private puppetlabs AMIs.

Ive been working on getting this working with Centos public AMIs. I'll create a PR when I have some tests written.

**Comment by tphoney** [comment]
Agreed setting up the test environment works for us at the minute. but needs work to help you out. 
When running the acceptance tests it will use the default.yml file in the nodesets folder.
Using the following command, 
BEAKER_set=debian-7-x64-vcloud bundle exec rspec spec/acceptance
allows you to call another nodeset called debian-7-x64-vcloud.yml
The tests should stay the same, but you will likely need a custom nodeset file

**Comment by davemcdonnell** [comment]
I got some tests working (Its been a bit of a missing getting beaker working but got there in the end).

I probably could have had a cut at writing tests without running them but feels better this way.

**Comment by tphoney** [comment]
thanks for the effort you put in. did you create a new nodeset ?

**Comment by davemcdonnell** [comment]
I hacked up the existing local.yml one. Using fusion as hypervisor for puppet host (and netscaler hypervisor for the netscaler VM).

I had to hard code my netscaler VM in spec_helper_acceptance.rb, this line was causing issues:
url https://nsroot:#{hosts_as('netscaler').first[:ssh][:password]}@#{hosts_as('netscaler').first['ip']}/nitro/v1/

hosts_as('netscaler') is returning an empty array.
I didnt thoroughly review the beaker code, but I have a feeling multiple hypervisors dont work properly. (Or at leasts ones that dont share a common "hosts" variable).

This is the nodeset I was using:
HOSTS:
  "debian":
    roles:
      - "master"
      - "default"
    platform: "debian-7-amd64"
    hypervisor: "none"
    template: "debian-7-x86_64"
    snapshot: "base"
    ip: 192.168.2.105
    vmhostname: debian.local
    "netscaler":
      roles:
        - "netscaler"
      vmname: "netscaler-10.1"
      hypervisor: "none"
      platform: "el-netscaler-10.1"
      ip: '192.168.2.10'
      ssh:
        password: 'nsroot'
CONFIG:
  type: "foss"
  log_level: "debug"
  ec2_yaml: "spec/acceptance/nodesets/ec2.yaml"

**Comment by tphoney** [comment]
if it was useful for you, it would be worth putting into the nodesets. Just give is a nice descriptive name. 

thanks again for the effort you put in.

**Pull request merged**
