### PR TITLE
Add sslserver bindings with ecccurve and sslcipher

### PR DESCRIPTION
**Pull request by jovandeginste**

### CODE REVIEW

**Comment by jonnytpuppet** [comment]
@jovandeginste Thanks for your contribution! This is an amazing PR!

Before we can merge this, it would be appreciated if you could add acceptance tests for these new types and providers. They are in the spec/acceptance directory and shouldn't be very difficult to add new ones based on the old ones.

Thanks!

**Comment by jonnytpuppet** [comment]
@hunner Just wanted to ping you to show you this epic PR :D

**Comment by jovandeginste** [comment]
@jonnytpuppet if only I knew how:

After installing the gems (bundle install), I get:

```
$ rake beaker                # Run beaker acceptance tests
```

Result:

```
$HOME/.rvm/rubies/ruby-2.1.5/bin/ruby -I$HOME/.rvm/gems/ruby-2.1.5@puppet-netscaler/gems/rspec-core-3.4.4/lib:$HOME/.rvm/gems/ruby-2.1.5@puppet-netscaler/gems/rspec-support-3.4.1/lib $HOME/.rvm/gems/ruby-2.1.5@puppet-netscaler/gems/rspec-core-3.4.4/exe/rspec spec/acceptance --color
$HOME/.rvm/gems/ruby-2.1.5@puppet-netscaler/gems/beaker-rspec-5.3.0/lib/beaker-rspec/helpers/serverspec.rb:43: warning: already initialized constant Module::VALID_OPTIONS_KEYS
$HOME/.rvm/gems/ruby-2.1.5@puppet-netscaler/gems/specinfra-2.57.2/lib/specinfra/configuration.rb:4: warning: previous definition of VALID_OPTIONS_KEYS was here
Hypervisor for puppet is ec2
Hypervisor for netscaler is ec2
Beaker::Hypervisor, found some ec2 boxes to create
$HOME/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - $HOME/.fog (Errno::ENOENT)

**Comment by jonnytpuppet** [comment]
@jovandeginste 

If you can just create a new file in spec/acceptance based on one of the other tests, I can run it here for you.

Cheers

**Comment by eputnam** [comment]
closing due to inactivity

**Pull request closed without merging**
