### PR TITLE
(DOC-1967) document puppet device

### PR DESCRIPTION
**Pull request by tkishel**
normalize setup of puppet agents used to run puppet device

correct markdown

### CODE REVIEW

**Comment by tphoney** [comment]
there seems to be repeated use of netscalar, not netscaler

**Comment by tkishel** [comment]
Thanks, I'll correct that when I return from vacation July 12. My past in mathematics is catching up to me... "What's the difference between a mountain climber and a mosquito? One's a scalar and one's a vector."

**Comment by tkishel** [comment]
Corrected netscalar

**Comment by jbondpdx** [comment]
@tphoney I reviewed this PR, and just merged the same thing for f5. So if you want to merge this one, it looks good to me.

**Pull request merged**
