### PR TITLE
Add new sslvserver

### PR DESCRIPTION
**Pull request by jovandeginste**
(Don't merge this if you didn't merge PR #182 !)

### CODE REVIEW

**Comment by jovandeginste** [comment]
squashed

**Comment by david22swan** [comment]
@jovandeginste Is there any movement on this PR?

**Comment by david22swan** [comment]
Closed by accident. Sorry

**Comment by david22swan** [comment]
@jovandeginste I apologize but due to the amount of tie that has gone by since this PR was last updated and your lack os response to attempts to communicate we feel that we must now close this PR. If at a later time you decide to return to it then we will be more than happy to once again review it.
Best Wishes

**Pull request closed without merging**
